
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name | quote }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: claim1
    namespace: manunagraj990-dev